[package]
name = "pixas"
version = "0.1.0"
edition = "2024"

[dependencies]
clap = { version = "4.0", features = ["derive"] }
image = "0.24"
imageproc = "0.24"
terminal_size = "0.3"

[profile.release]
lto = true
strip = true
opt-level = 3
